package auth

// ConfigEnabled converts a SQLite INTEGER-backed boolean column
// (as generated by sqlc for oidc_config.enabled / ldap_config.enabled)
// into a bool.
func ConfigEnabled(value int64) bool {
	return value == 1
}