// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"
)

const createAuditLog = `-- name: CreateAuditLog :exec
INSERT INTO audit_log (actor_user_id, action, target_type, target_id, detail)
VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5
)
`

type CreateAuditLogParams struct {
	ActorUserID *int64  `json:"actor_user_id"`
	Action      string  `json:"action"`
	TargetType  *string `json:"target_type"`
	TargetID    *string `json:"target_id"`
	Detail      *string `json:"detail"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error {
	_, err := q.db.ExecContext(ctx, createAuditLog,
		arg.ActorUserID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Detail,
	)
	return err
}
