// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: config.sql

package db

import (
	"context"
)

const getLDAPConfig = `-- name: GetLDAPConfig :one
SELECT id, enabled, server, port, base_dn, bind_dn, bind_password, user_filter FROM ldap_config WHERE id = 1
`

func (q *Queries) GetLDAPConfig(ctx context.Context) (LdapConfig, error) {
	row := q.db.QueryRowContext(ctx, getLDAPConfig)
	var i LdapConfig
	err := row.Scan(
		&i.ID,
		&i.Enabled,
		&i.Server,
		&i.Port,
		&i.BaseDn,
		&i.BindDn,
		&i.BindPassword,
		&i.UserFilter,
	)
	return i, err
}

const getOIDCConfig = `-- name: GetOIDCConfig :one
SELECT id, enabled, issuer_url, client_id, client_secret, redirect_url FROM oidc_config WHERE id = 1
`

func (q *Queries) GetOIDCConfig(ctx context.Context) (OidcConfig, error) {
	row := q.db.QueryRowContext(ctx, getOIDCConfig)
	var i OidcConfig
	err := row.Scan(
		&i.ID,
		&i.Enabled,
		&i.IssuerUrl,
		&i.ClientID,
		&i.ClientSecret,
		&i.RedirectUrl,
	)
	return i, err
}
