// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type AuditLog struct {
	ID          int64   `json:"id"`
	ActorUserID *int64  `json:"actor_user_id"`
	Action      string  `json:"action"`
	TargetType  *string `json:"target_type"`
	TargetID    *string `json:"target_id"`
	Detail      *string `json:"detail"`
	CreatedAt   string  `json:"created_at"`
}

type DecommissionRequest struct {
	ID          int64   `json:"id"`
	RequestID   int64   `json:"request_id"`
	RequestedBy int64   `json:"requested_by"`
	Reason      *string `json:"reason"`
	Status      string  `json:"status"`
	DecidedBy   *int64  `json:"decided_by"`
	DecidedAt   *string `json:"decided_at"`
	CreatedAt   string  `json:"created_at"`
}

type IpAllocation struct {
	ID          int64   `json:"id"`
	SubnetID    int64   `json:"subnet_id"`
	IpAddress   string  `json:"ip_address"`
	RequestID   *int64  `json:"request_id"`
	AllocatedAt string  `json:"allocated_at"`
	ReleasedAt  *string `json:"released_at"`
}

type NamingScheme struct {
	ID          int64  `json:"id"`
	Name        string `json:"name"`
	Template    string `json:"template"`
	TokenLength int64  `json:"token_length"`
	SeqLength   int64  `json:"seq_length"`
	TotalLength int64  `json:"total_length"`
}

type NamingSchemeTokenValue struct {
	ID       int64  `json:"id"`
	SchemeID int64  `json:"scheme_id"`
	Token    string `json:"token"`
	Code     string `json:"code"`
	Label    string `json:"label"`
	Active   int64  `json:"active"`
}

type NamingSequence struct {
	ID             int64  `json:"id"`
	SchemeID       int64  `json:"scheme_id"`
	ComputedPrefix string `json:"computed_prefix"`
	LastSeq        int64  `json:"last_seq"`
}

type Request struct {
	ID             int64   `json:"id"`
	RequesterID    int64   `json:"requester_id"`
	NamingSchemeID int64   `json:"naming_scheme_id"`
	SiteCode       string  `json:"site_code"`
	EnvCode        string  `json:"env_code"`
	AppCode        string  `json:"app_code"`
	RoleCode       string  `json:"role_code"`
	Status         string  `json:"status"`
	GeneratedName  *string `json:"generated_name"`
	AllocatedIp    *string `json:"allocated_ip"`
	CreatedAt      string  `json:"created_at"`
	DecidedBy      *int64  `json:"decided_by"`
	DecidedAt      *string `json:"decided_at"`
}

type Role struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type Session struct {
	Token  string  `json:"token"`
	Data   []byte  `json:"data"`
	Expiry float64 `json:"expiry"`
}

type SiteEnvSubnetMap struct {
	ID       int64  `json:"id"`
	SiteCode string `json:"site_code"`
	EnvCode  string `json:"env_code"`
	SubnetID int64  `json:"subnet_id"`
	Active   int64  `json:"active"`
}

type Subnet struct {
	ID        int64   `json:"id"`
	Cidr      string  `json:"cidr"`
	Label     *string `json:"label"`
	Active    int64   `json:"active"`
	CreatedAt string  `json:"created_at"`
}

type SubnetReservedIp struct {
	ID        int64   `json:"id"`
	SubnetID  int64   `json:"subnet_id"`
	IpAddress string  `json:"ip_address"`
	Reason    *string `json:"reason"`
	CreatedAt string  `json:"created_at"`
}

type User struct {
	ID           int64   `json:"id"`
	DisplayName  string  `json:"display_name"`
	Email        *string `json:"email"`
	AuthSource   string  `json:"auth_source"`
	OidcSubject  *string `json:"oidc_subject"`
	PasswordHash *string `json:"password_hash"`
	Active       int64   `json:"active"`
	CreatedAt    string  `json:"created_at"`
}

type UserRole struct {
	UserID int64 `json:"user_id"`
	RoleID int64 `json:"role_id"`
}
