// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type ApiKey struct {
	ID         int64   `json:"id"`
	Label      string  `json:"label"`
	KeyHash    string  `json:"key_hash"`
	Scope      string  `json:"scope"`
	CreatedBy  *int64  `json:"created_by"`
	CreatedAt  string  `json:"created_at"`
	LastUsedAt *string `json:"last_used_at"`
	RevokedAt  *string `json:"revoked_at"`
}

type AuditLog struct {
	ID          int64   `json:"id"`
	ActorUserID *int64  `json:"actor_user_id"`
	Action      string  `json:"action"`
	TargetType  *string `json:"target_type"`
	TargetID    *string `json:"target_id"`
	Detail      *string `json:"detail"`
	CreatedAt   string  `json:"created_at"`
}

type DecommissionRequest struct {
	ID          int64   `json:"id"`
	RequestID   int64   `json:"request_id"`
	RequestedBy int64   `json:"requested_by"`
	Reason      *string `json:"reason"`
	Status      string  `json:"status"`
	DecidedBy   *int64  `json:"decided_by"`
	DecidedAt   *string `json:"decided_at"`
	CreatedAt   string  `json:"created_at"`
}

type IpAllocation struct {
	ID          int64   `json:"id"`
	SubnetID    int64   `json:"subnet_id"`
	IpAddress   string  `json:"ip_address"`
	RequestID   *int64  `json:"request_id"`
	ServerID    *int64  `json:"server_id"`
	AllocatedAt string  `json:"allocated_at"`
	ReleasedAt  *string `json:"released_at"`
}

type LdapConfig struct {
	ID           int64   `json:"id"`
	Enabled      int64   `json:"enabled"`
	Server       *string `json:"server"`
	Port         *int64  `json:"port"`
	BaseDn       *string `json:"base_dn"`
	BindDn       *string `json:"bind_dn"`
	BindPassword *string `json:"bind_password"`
	UserFilter   *string `json:"user_filter"`
}

type MaintenanceWindow struct {
	ID              int64   `json:"id"`
	Label           string  `json:"label"`
	Rrule           *string `json:"rrule"`
	Dtstart         string  `json:"dtstart"`
	DurationMinutes int64   `json:"duration_minutes"`
	Timezone        string  `json:"timezone"`
	CreatedBy       *int64  `json:"created_by"`
	CreatedAt       string  `json:"created_at"`
}

type MaintenanceWindowServer struct {
	WindowID int64 `json:"window_id"`
	ServerID int64 `json:"server_id"`
}

type NamingScheme struct {
	ID          int64  `json:"id"`
	Name        string `json:"name"`
	Template    string `json:"template"`
	TokenLength int64  `json:"token_length"`
	SeqLength   int64  `json:"seq_length"`
	TotalLength int64  `json:"total_length"`
}

type NamingSchemeTokenValue struct {
	ID       int64  `json:"id"`
	SchemeID int64  `json:"scheme_id"`
	Token    string `json:"token"`
	Code     string `json:"code"`
	Label    string `json:"label"`
	Active   int64  `json:"active"`
}

type NamingSequence struct {
	ID             int64  `json:"id"`
	SchemeID       int64  `json:"scheme_id"`
	ComputedPrefix string `json:"computed_prefix"`
	LastSeq        int64  `json:"last_seq"`
}

type OidcConfig struct {
	ID           int64   `json:"id"`
	Enabled      int64   `json:"enabled"`
	IssuerUrl    *string `json:"issuer_url"`
	ClientID     *string `json:"client_id"`
	ClientSecret *string `json:"client_secret"`
	RedirectUrl  *string `json:"redirect_url"`
}

type Request struct {
	ID             int64   `json:"id"`
	RequesterID    int64   `json:"requester_id"`
	NamingSchemeID int64   `json:"naming_scheme_id"`
	SiteCode       string  `json:"site_code"`
	EnvCode        string  `json:"env_code"`
	AppCode        string  `json:"app_code"`
	RoleCode       string  `json:"role_code"`
	Status         string  `json:"status"`
	GeneratedName  *string `json:"generated_name"`
	AllocatedIp    *string `json:"allocated_ip"`
	CreatedAt      string  `json:"created_at"`
	DecidedBy      *int64  `json:"decided_by"`
	DecidedAt      *string `json:"decided_at"`
}

type Role struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type Server struct {
	ID          int64   `json:"id"`
	Hostname    string  `json:"hostname"`
	RequestID   *int64  `json:"request_id"`
	Description *string `json:"description"`
	CreatedBy   *int64  `json:"created_by"`
	CreatedAt   string  `json:"created_at"`
}

type Session struct {
	Token  string  `json:"token"`
	Data   []byte  `json:"data"`
	Expiry float64 `json:"expiry"`
}

type SiteEnvSubnetMap struct {
	ID       int64  `json:"id"`
	SiteCode string `json:"site_code"`
	EnvCode  string `json:"env_code"`
	SubnetID int64  `json:"subnet_id"`
	Active   int64  `json:"active"`
}

type Subnet struct {
	ID        int64   `json:"id"`
	Cidr      string  `json:"cidr"`
	Label     *string `json:"label"`
	Active    int64   `json:"active"`
	CreatedAt string  `json:"created_at"`
}

type SubnetReservedIp struct {
	ID        int64   `json:"id"`
	SubnetID  int64   `json:"subnet_id"`
	IpAddress string  `json:"ip_address"`
	Reason    *string `json:"reason"`
	CreatedAt string  `json:"created_at"`
}

type User struct {
	ID           int64   `json:"id"`
	DisplayName  string  `json:"display_name"`
	Email        *string `json:"email"`
	AuthSource   string  `json:"auth_source"`
	OidcSubject  *string `json:"oidc_subject"`
	PasswordHash *string `json:"password_hash"`
	Active       int64   `json:"active"`
	CreatedAt    string  `json:"created_at"`
}

type UserRole struct {
	UserID int64 `json:"user_id"`
	RoleID int64 `json:"role_id"`
}
