// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: naming.sql

package db

import (
	"context"
)

const createNamingSchemeTokenValue = `-- name: CreateNamingSchemeTokenValue :one
INSERT INTO naming_scheme_token_values (scheme_id, token, code, label)
VALUES (?1, ?2, UPPER(?3), ?4)
RETURNING id, scheme_id, token, code, label, active
`

type CreateNamingSchemeTokenValueParams struct {
	SchemeID int64  `json:"scheme_id"`
	Token    string `json:"token"`
	Code     string `json:"code"`
	Label    string `json:"label"`
}

// UPPER(?) on code -- see queries.instructions.md's
// "Reference: naming scheme queries (IPAM-16/17)" section.
func (q *Queries) CreateNamingSchemeTokenValue(ctx context.Context, arg CreateNamingSchemeTokenValueParams) (NamingSchemeTokenValue, error) {
	row := q.db.QueryRowContext(ctx, createNamingSchemeTokenValue,
		arg.SchemeID,
		arg.Token,
		arg.Code,
		arg.Label,
	)
	var i NamingSchemeTokenValue
	err := row.Scan(
		&i.ID,
		&i.SchemeID,
		&i.Token,
		&i.Code,
		&i.Label,
		&i.Active,
	)
	return i, err
}

const createSiteEnvSubnetMap = `-- name: CreateSiteEnvSubnetMap :one
INSERT INTO site_env_subnet_map (site_code, env_code, naming_scheme_id, subnet_id, active)
VALUES (?1, ?2, ?3, ?4, 1)
RETURNING id, site_code, env_code, naming_scheme_id, subnet_id, active
`

type CreateSiteEnvSubnetMapParams struct {
	SiteCode       string `json:"site_code"`
	EnvCode        string `json:"env_code"`
	NamingSchemeID int64  `json:"naming_scheme_id"`
	SubnetID       int64  `json:"subnet_id"`
}

func (q *Queries) CreateSiteEnvSubnetMap(ctx context.Context, arg CreateSiteEnvSubnetMapParams) (SiteEnvSubnetMap, error) {
	row := q.db.QueryRowContext(ctx, createSiteEnvSubnetMap,
		arg.SiteCode,
		arg.EnvCode,
		arg.NamingSchemeID,
		arg.SubnetID,
	)
	var i SiteEnvSubnetMap
	err := row.Scan(
		&i.ID,
		&i.SiteCode,
		&i.EnvCode,
		&i.NamingSchemeID,
		&i.SubnetID,
		&i.Active,
	)
	return i, err
}

const deactivateNamingSchemeTokenValue = `-- name: DeactivateNamingSchemeTokenValue :exec
UPDATE naming_scheme_token_values
SET active = 0
WHERE id = ?1 AND scheme_id = ?2
`

type DeactivateNamingSchemeTokenValueParams struct {
	ID       int64 `json:"id"`
	SchemeID int64 `json:"scheme_id"`
}

// Deactivate, never delete -- a request can still reference an inactive
// code's historical value. Scoped by scheme_id too, same
// belt-and-suspenders pattern as DeleteSubnetReservedIP.
func (q *Queries) DeactivateNamingSchemeTokenValue(ctx context.Context, arg DeactivateNamingSchemeTokenValueParams) error {
	_, err := q.db.ExecContext(ctx, deactivateNamingSchemeTokenValue, arg.ID, arg.SchemeID)
	return err
}

const getNamingScheme = `-- name: GetNamingScheme :one
SELECT id, name, naming_mode, template, token_length, seq_length, total_length
FROM naming_schemes WHERE id = ?1
`

type GetNamingSchemeRow struct {
	ID          int64   `json:"id"`
	Name        string  `json:"name"`
	NamingMode  string  `json:"naming_mode"`
	Template    *string `json:"template"`
	TokenLength int64   `json:"token_length"`
	SeqLength   int64   `json:"seq_length"`
	TotalLength int64   `json:"total_length"`
}

func (q *Queries) GetNamingScheme(ctx context.Context, id int64) (GetNamingSchemeRow, error) {
	row := q.db.QueryRowContext(ctx, getNamingScheme, id)
	var i GetNamingSchemeRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NamingMode,
		&i.Template,
		&i.TokenLength,
		&i.SeqLength,
		&i.TotalLength,
	)
	return i, err
}

const getSiteEnvSubnetMap = `-- name: GetSiteEnvSubnetMap :one
SELECT id, site_code, env_code, naming_scheme_id, subnet_id, active FROM site_env_subnet_map WHERE id = ?1
`

func (q *Queries) GetSiteEnvSubnetMap(ctx context.Context, id int64) (SiteEnvSubnetMap, error) {
	row := q.db.QueryRowContext(ctx, getSiteEnvSubnetMap, id)
	var i SiteEnvSubnetMap
	err := row.Scan(
		&i.ID,
		&i.SiteCode,
		&i.EnvCode,
		&i.NamingSchemeID,
		&i.SubnetID,
		&i.Active,
	)
	return i, err
}

const listActiveSiteEnvTokenValues = `-- name: ListActiveSiteEnvTokenValues :many
SELECT scheme_id, token, code, label
FROM naming_scheme_token_values
WHERE active = 1 AND token IN ('site', 'env')
ORDER BY scheme_id, token, code
`

type ListActiveSiteEnvTokenValuesRow struct {
	SchemeID int64  `json:"scheme_id"`
	Token    string `json:"token"`
	Code     string `json:"code"`
	Label    string `json:"label"`
}

// Load active site and env tokens for client-side filtering by scheme and token.
func (q *Queries) ListActiveSiteEnvTokenValues(ctx context.Context) ([]ListActiveSiteEnvTokenValuesRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveSiteEnvTokenValues)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveSiteEnvTokenValuesRow{}
	for rows.Next() {
		var i ListActiveSiteEnvTokenValuesRow
		if err := rows.Scan(
			&i.SchemeID,
			&i.Token,
			&i.Code,
			&i.Label,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNamingSchemeTokenValues = `-- name: ListNamingSchemeTokenValues :many
SELECT id, token, code, label, active
FROM naming_scheme_token_values
WHERE scheme_id = ?1
ORDER BY token, code
`

type ListNamingSchemeTokenValuesRow struct {
	ID     int64  `json:"id"`
	Token  string `json:"token"`
	Code   string `json:"code"`
	Label  string `json:"label"`
	Active int64  `json:"active"`
}

// ORDER BY token, code -- no lexicographic-sort trap here (unlike
// ip_address/reserved-ips): code is a fixed-length, non-numeric 3-char
// abbreviation, so plain string ordering is correct, not just convenient.
func (q *Queries) ListNamingSchemeTokenValues(ctx context.Context, schemeID int64) ([]ListNamingSchemeTokenValuesRow, error) {
	rows, err := q.db.QueryContext(ctx, listNamingSchemeTokenValues, schemeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNamingSchemeTokenValuesRow{}
	for rows.Next() {
		var i ListNamingSchemeTokenValuesRow
		if err := rows.Scan(
			&i.ID,
			&i.Token,
			&i.Code,
			&i.Label,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNamingSchemes = `-- name: ListNamingSchemes :many
SELECT id, name, naming_mode, template FROM naming_schemes ORDER BY id
`

type ListNamingSchemesRow struct {
	ID         int64   `json:"id"`
	Name       string  `json:"name"`
	NamingMode string  `json:"naming_mode"`
	Template   *string `json:"template"`
}

func (q *Queries) ListNamingSchemes(ctx context.Context) ([]ListNamingSchemesRow, error) {
	rows, err := q.db.QueryContext(ctx, listNamingSchemes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNamingSchemesRow{}
	for rows.Next() {
		var i ListNamingSchemesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NamingMode,
			&i.Template,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSiteEnvSubnetMapWithDetails = `-- name: ListSiteEnvSubnetMapWithDetails :many
SELECT
    m.id,
    m.site_code,
    m.env_code,
    m.active,
    ns.id   AS scheme_id,
    ns.name AS scheme_name,
    s.id    AS subnet_id,
    s.cidr  AS subnet_cidr,
    s.label AS subnet_label,
    COUNT(DISTINCT sr.id) AS reserved_count,
    COUNT(DISTINCT ia.id) AS used_count
FROM site_env_subnet_map m
JOIN naming_schemes ns ON ns.id = m.naming_scheme_id
JOIN subnets s ON s.id = m.subnet_id
LEFT JOIN subnet_reserved_ips sr ON sr.subnet_id = s.id
LEFT JOIN ip_allocations ia ON ia.subnet_id = s.id AND ia.released_at IS NULL
GROUP BY m.id
ORDER BY ns.name, m.site_code, m.env_code
`

type ListSiteEnvSubnetMapWithDetailsRow struct {
	ID            int64   `json:"id"`
	SiteCode      string  `json:"site_code"`
	EnvCode       string  `json:"env_code"`
	Active        int64   `json:"active"`
	SchemeID      int64   `json:"scheme_id"`
	SchemeName    string  `json:"scheme_name"`
	SubnetID      int64   `json:"subnet_id"`
	SubnetCidr    string  `json:"subnet_cidr"`
	SubnetLabel   *string `json:"subnet_label"`
	ReservedCount int64   `json:"reserved_count"`
	UsedCount     int64   `json:"used_count"`
}

// Include scheme and subnet details for the mapping list page.
func (q *Queries) ListSiteEnvSubnetMapWithDetails(ctx context.Context) ([]ListSiteEnvSubnetMapWithDetailsRow, error) {
	rows, err := q.db.QueryContext(ctx, listSiteEnvSubnetMapWithDetails)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSiteEnvSubnetMapWithDetailsRow{}
	for rows.Next() {
		var i ListSiteEnvSubnetMapWithDetailsRow
		if err := rows.Scan(
			&i.ID,
			&i.SiteCode,
			&i.EnvCode,
			&i.Active,
			&i.SchemeID,
			&i.SchemeName,
			&i.SubnetID,
			&i.SubnetCidr,
			&i.SubnetLabel,
			&i.ReservedCount,
			&i.UsedCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSiteEnvSubnetMap = `-- name: UpdateSiteEnvSubnetMap :exec
UPDATE site_env_subnet_map
SET site_code = ?1, env_code = ?2,
    naming_scheme_id = ?3, subnet_id = ?4,
    active = ?5
WHERE id = ?6
`

type UpdateSiteEnvSubnetMapParams struct {
	SiteCode       string `json:"site_code"`
	EnvCode        string `json:"env_code"`
	NamingSchemeID int64  `json:"naming_scheme_id"`
	SubnetID       int64  `json:"subnet_id"`
	Active         int64  `json:"active"`
	ID             int64  `json:"id"`
}

func (q *Queries) UpdateSiteEnvSubnetMap(ctx context.Context, arg UpdateSiteEnvSubnetMapParams) error {
	_, err := q.db.ExecContext(ctx, updateSiteEnvSubnetMap,
		arg.SiteCode,
		arg.EnvCode,
		arg.NamingSchemeID,
		arg.SubnetID,
		arg.Active,
		arg.ID,
	)
	return err
}
