// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	AssignViewerRole(ctx context.Context, userID int64) error
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error
	CreateLDAPUser(ctx context.Context, arg CreateLDAPUserParams) (User, error)
	CreateLocalAdminUser(ctx context.Context, passwordHash *string) (User, error)
	CreateOIDCUser(ctx context.Context, arg CreateOIDCUserParams) (User, error)
	GetLDAPConfig(ctx context.Context) (LdapConfig, error)
	GetLDAPUser(ctx context.Context, ldapDn *string) (User, error)
	GetLocalAdminUser(ctx context.Context) (User, error)
	GetOIDCConfig(ctx context.Context) (OidcConfig, error)
	GetOIDCUser(ctx context.Context, oidcSubject *string) (User, error)
	GetUserRoleNames(ctx context.Context, userID int64) ([]string, error)
	UpdateLDAPConfig(ctx context.Context, arg UpdateLDAPConfigParams) error
	UpdateOIDCConfig(ctx context.Context, arg UpdateOIDCConfigParams) error
	UpdateUserPasswordHash(ctx context.Context, arg UpdateUserPasswordHashParams) error
}

var _ Querier = (*Queries)(nil)
