// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: requests.sql

package db

import (
	"context"
)

const createRequest = `-- name: CreateRequest :one
INSERT INTO requests (requester_id, naming_scheme_id, site_code, env_code, app_code, role_code, manual_name, status)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, 'pending')
RETURNING id, requester_id, naming_scheme_id, site_code, env_code, app_code, role_code, manual_name, status, generated_name, allocated_ip, created_at, decided_by, decided_at
`

type CreateRequestParams struct {
	RequesterID    int64   `json:"requester_id"`
	NamingSchemeID int64   `json:"naming_scheme_id"`
	SiteCode       string  `json:"site_code"`
	EnvCode        string  `json:"env_code"`
	AppCode        *string `json:"app_code"`
	RoleCode       *string `json:"role_code"`
	ManualName     *string `json:"manual_name"`
}

func (q *Queries) CreateRequest(ctx context.Context, arg CreateRequestParams) (Request, error) {
	row := q.db.QueryRowContext(ctx, createRequest,
		arg.RequesterID,
		arg.NamingSchemeID,
		arg.SiteCode,
		arg.EnvCode,
		arg.AppCode,
		arg.RoleCode,
		arg.ManualName,
	)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.RequesterID,
		&i.NamingSchemeID,
		&i.SiteCode,
		&i.EnvCode,
		&i.AppCode,
		&i.RoleCode,
		&i.ManualName,
		&i.Status,
		&i.GeneratedName,
		&i.AllocatedIp,
		&i.CreatedAt,
		&i.DecidedBy,
		&i.DecidedAt,
	)
	return i, err
}
