// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subnets.sql

package db

import (
	"context"
)

const countActiveAllocationsForSubnet = `-- name: CountActiveAllocationsForSubnet :one
SELECT COUNT(*) FROM ip_allocations WHERE subnet_id = ? AND released_at IS NULL
`

// Used for the deactivate warning: how many currently-active allocations
// would be "orphaned" (still valid, but on a subnet no longer accepting
// new ones) if this subnet is soft-retired. Informational only --
// does not block deactivation.
func (q *Queries) CountActiveAllocationsForSubnet(ctx context.Context, subnetID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveAllocationsForSubnet, subnetID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSubnet = `-- name: CreateSubnet :one
INSERT INTO subnets (cidr, label, active)
VALUES (?, ?, 1)
RETURNING id, cidr, label, active, created_at
`

type CreateSubnetParams struct {
	Cidr  string  `json:"cidr"`
	Label *string `json:"label"`
}

func (q *Queries) CreateSubnet(ctx context.Context, arg CreateSubnetParams) (Subnet, error) {
	row := q.db.QueryRowContext(ctx, createSubnet, arg.Cidr, arg.Label)
	var i Subnet
	err := row.Scan(
		&i.ID,
		&i.Cidr,
		&i.Label,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const getSubnet = `-- name: GetSubnet :one
SELECT id, cidr, label, active, created_at FROM subnets WHERE id = ?
`

func (q *Queries) GetSubnet(ctx context.Context, id int64) (Subnet, error) {
	row := q.db.QueryRowContext(ctx, getSubnet, id)
	var i Subnet
	err := row.Scan(
		&i.ID,
		&i.Cidr,
		&i.Label,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveSubnets = `-- name: ListActiveSubnets :many
SELECT id, cidr FROM subnets WHERE active = 1
`

type ListActiveSubnetsRow struct {
	ID   int64  `json:"id"`
	Cidr string `json:"cidr"`
}

// Used for CIDR overlap validation on create/edit -- only ACTIVE subnets
// are checked, per subnets.active semantics: a retired range can be
// legitimately reused by a new subnet without being falsely blocked by
// its own retired history.
func (q *Queries) ListActiveSubnets(ctx context.Context) ([]ListActiveSubnetsRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveSubnets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveSubnetsRow{}
	for rows.Next() {
		var i ListActiveSubnetsRow
		if err := rows.Scan(&i.ID, &i.Cidr); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubnetsWithCounts = `-- name: ListSubnetsWithCounts :many
SELECT
    s.id,
    s.cidr,
    s.label,
    s.active,
    COUNT(DISTINCT sr.id) AS reserved_count,
    COUNT(DISTINCT ia.id) AS used_count,
    CAST(COALESCE(GROUP_CONCAT(DISTINCT sem.site_code || '/' || sem.env_code), '') AS TEXT) AS site_envs
FROM subnets s
LEFT JOIN subnet_reserved_ips sr ON sr.subnet_id = s.id
LEFT JOIN ip_allocations ia ON ia.subnet_id = s.id AND ia.released_at IS NULL
LEFT JOIN site_env_subnet_map sem ON sem.subnet_id = s.id AND sem.active = 1
GROUP BY s.id
ORDER BY s.cidr
`

type ListSubnetsWithCountsRow struct {
	ID            int64   `json:"id"`
	Cidr          string  `json:"cidr"`
	Label         *string `json:"label"`
	Active        int64   `json:"active"`
	ReservedCount int64   `json:"reserved_count"`
	UsedCount     int64   `json:"used_count"`
	SiteEnvs      string  `json:"site_envs"`
}

// Three LEFT JOINs (reserved IPs, active allocations, active site+env
// mappings) produce a cross product of matching rows per subnet. Each
// aggregate below is DISTINCT on its own join's identifying value, so
// extra rows introduced by the OTHER joins never inflate a given
// aggregate. Do not change these to plain COUNT(*)/GROUP_CONCAT(*) --
// the numbers will look plausible but be wrong.
//
// site_envs is wrapped in CAST(... AS TEXT): sqlc's type inferencer
// can't determine a concrete type for COALESCE(GROUP_CONCAT(...), ”)
// on its own and falls back to interface{} (loses type safety). The
// explicit CAST forces a clean string inference instead. COALESCE
// handles the NULL GROUP_CONCAT returns when a subnet has zero matching
// mapping rows. GROUP_CONCAT(DISTINCT ...) can only take one argument in
// SQLite -- a custom separator is NOT allowed alongside DISTINCT, so
// this comes back comma-separated with no space; formatted for display
// (", ") in Go instead, see displaySiteEnvs in the admin view.
func (q *Queries) ListSubnetsWithCounts(ctx context.Context) ([]ListSubnetsWithCountsRow, error) {
	rows, err := q.db.QueryContext(ctx, listSubnetsWithCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSubnetsWithCountsRow{}
	for rows.Next() {
		var i ListSubnetsWithCountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Cidr,
			&i.Label,
			&i.Active,
			&i.ReservedCount,
			&i.UsedCount,
			&i.SiteEnvs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSubnet = `-- name: UpdateSubnet :exec
UPDATE subnets SET cidr = ?, label = ?, active = ? WHERE id = ?
`

type UpdateSubnetParams struct {
	Cidr   string  `json:"cidr"`
	Label  *string `json:"label"`
	Active int64   `json:"active"`
	ID     int64   `json:"id"`
}

func (q *Queries) UpdateSubnet(ctx context.Context, arg UpdateSubnetParams) error {
	_, err := q.db.ExecContext(ctx, updateSubnet,
		arg.Cidr,
		arg.Label,
		arg.Active,
		arg.ID,
	)
	return err
}
