// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
)

const assignViewerRole = `-- name: AssignViewerRole :exec
INSERT OR IGNORE INTO user_roles (user_id, role_id)
SELECT ?1, id FROM roles WHERE name = 'viewer'
`

func (q *Queries) AssignViewerRole(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, assignViewerRole, userID)
	return err
}

const createLDAPUser = `-- name: CreateLDAPUser :one
INSERT INTO users (display_name, email, auth_source, ldap_dn, active)
VALUES (?1, ?2, 'ldap', ?3, 1)
RETURNING id, display_name, email, auth_source, oidc_subject, ldap_dn, password_hash, active, created_at
`

type CreateLDAPUserParams struct {
	DisplayName string  `json:"display_name"`
	Email       *string `json:"email"`
	LdapDn      *string `json:"ldap_dn"`
}

func (q *Queries) CreateLDAPUser(ctx context.Context, arg CreateLDAPUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createLDAPUser, arg.DisplayName, arg.Email, arg.LdapDn)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Email,
		&i.AuthSource,
		&i.OidcSubject,
		&i.LdapDn,
		&i.PasswordHash,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const createLocalAdminUser = `-- name: CreateLocalAdminUser :one
INSERT INTO users (display_name, auth_source, password_hash, active)
VALUES ('administrator', 'local', ?1, 1)
RETURNING id, display_name, email, auth_source, oidc_subject, ldap_dn, password_hash, active, created_at
`

func (q *Queries) CreateLocalAdminUser(ctx context.Context, passwordHash *string) (User, error) {
	row := q.db.QueryRowContext(ctx, createLocalAdminUser, passwordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Email,
		&i.AuthSource,
		&i.OidcSubject,
		&i.LdapDn,
		&i.PasswordHash,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const createOIDCUser = `-- name: CreateOIDCUser :one
INSERT INTO users (display_name, email, auth_source, oidc_subject, active)
VALUES (?1, ?2, 'oidc', ?3, 1)
RETURNING id, display_name, email, auth_source, oidc_subject, ldap_dn, password_hash, active, created_at
`

type CreateOIDCUserParams struct {
	DisplayName string  `json:"display_name"`
	Email       *string `json:"email"`
	OidcSubject *string `json:"oidc_subject"`
}

func (q *Queries) CreateOIDCUser(ctx context.Context, arg CreateOIDCUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createOIDCUser, arg.DisplayName, arg.Email, arg.OidcSubject)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Email,
		&i.AuthSource,
		&i.OidcSubject,
		&i.LdapDn,
		&i.PasswordHash,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const getLDAPUser = `-- name: GetLDAPUser :one
SELECT id, display_name, email, auth_source, oidc_subject, ldap_dn, password_hash, active, created_at FROM users
WHERE auth_source = 'ldap' AND ldap_dn = ?1
LIMIT 1
`

func (q *Queries) GetLDAPUser(ctx context.Context, ldapDn *string) (User, error) {
	row := q.db.QueryRowContext(ctx, getLDAPUser, ldapDn)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Email,
		&i.AuthSource,
		&i.OidcSubject,
		&i.LdapDn,
		&i.PasswordHash,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const getLocalAdminUser = `-- name: GetLocalAdminUser :one
SELECT id, display_name, email, auth_source, oidc_subject, ldap_dn, password_hash, active, created_at FROM users WHERE auth_source = 'local' LIMIT 1
`

func (q *Queries) GetLocalAdminUser(ctx context.Context) (User, error) {
	row := q.db.QueryRowContext(ctx, getLocalAdminUser)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Email,
		&i.AuthSource,
		&i.OidcSubject,
		&i.LdapDn,
		&i.PasswordHash,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const getOIDCUser = `-- name: GetOIDCUser :one
SELECT id, display_name, email, auth_source, oidc_subject, ldap_dn, password_hash, active, created_at FROM users
WHERE auth_source = 'oidc' AND oidc_subject = ?1
LIMIT 1
`

func (q *Queries) GetOIDCUser(ctx context.Context, oidcSubject *string) (User, error) {
	row := q.db.QueryRowContext(ctx, getOIDCUser, oidcSubject)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Email,
		&i.AuthSource,
		&i.OidcSubject,
		&i.LdapDn,
		&i.PasswordHash,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const getUserRoleNames = `-- name: GetUserRoleNames :many
SELECT r.name FROM roles r
JOIN user_roles ur ON ur.role_id = r.id
WHERE ur.user_id = ?1
`

func (q *Queries) GetUserRoleNames(ctx context.Context, userID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getUserRoleNames, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserPasswordHash = `-- name: UpdateUserPasswordHash :exec
UPDATE users
SET password_hash = ?1
WHERE id = ?2
`

type UpdateUserPasswordHashParams struct {
	PasswordHash *string `json:"password_hash"`
	ID           int64   `json:"id"`
}

func (q *Queries) UpdateUserPasswordHash(ctx context.Context, arg UpdateUserPasswordHashParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPasswordHash, arg.PasswordHash, arg.ID)
	return err
}
