// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
)

const listRoleNamesByUserID = `-- name: ListRoleNamesByUserID :many
SELECT roles.name
FROM roles
JOIN user_roles ON user_roles.role_id = roles.id
WHERE user_roles.user_id = ?
ORDER BY roles.name ASC
`

func (q *Queries) ListRoleNamesByUserID(ctx context.Context, userID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listRoleNamesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
